//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeRange
    {
        public int CodeRangeId { get; set; }
        public Nullable<int> MinCode { get; set; }
        public Nullable<int> MaxCode { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
