//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ContentId { get; set; }
        public Nullable<int> ContentTypeId { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> EditorId { get; set; }
        public Nullable<int> FileTypeId { get; set; }
        public Nullable<int> FileNumber { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<int> WorkFlowStateId { get; set; }
        public string DeletionDescription { get; set; }
        public string Comment { get; set; }
        public string Text { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual Editor Editor { get; set; }
        public virtual FileType FileType { get; set; }
        public virtual Document Document { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
