//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public int ViewId { get; set; }
        public string ViewTitle { get; set; }
        public string ViewText { get; set; }
        public int SenderUserId { get; set; }
        public int ReceiverUserId { get; set; }
        public string SendDate { get; set; }
        public string ReceiveDate { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
    }
}
