//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Contents = new HashSet<Content>();
            this.DocumentNarratorRelations = new HashSet<DocumentNarratorRelation>();
            this.DocumentResourceRelations = new HashSet<DocumentResourceRelation>();
            this.DocumentSubjectRelations = new HashSet<DocumentSubjectRelation>();
        }
    
        public int DocumentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string DocumentCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SiteCode { get; set; }
        public string OldTitle { get; set; }
        public string NewTitle { get; set; }
        public string SubTitle { get; set; }
        public Nullable<int> PublishStateId { get; set; }
        public Nullable<int> PermissionStateId { get; set; }
        public Nullable<int> CreatorUserId { get; set; }
        public Nullable<int> PadidAvarId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CollectionId { get; set; }
        public Nullable<int> SessionNumber { get; set; }
        public Nullable<int> SessionCount { get; set; }
        public string SessionPlace { get; set; }
        public Nullable<System.DateTime> SessionDate { get; set; }
        public string RelatedLink { get; set; }
        public string Description { get; set; }
        public Nullable<int> MainCategoryId { get; set; }
        public Nullable<int> ContentTypeId { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public Nullable<int> BookVolumeNumber { get; set; }
        public Nullable<int> BookPageCount { get; set; }
        public Nullable<int> BookVolumeCount { get; set; }
        public string FipaCode { get; set; }
        public Nullable<int> TranslateLanguageId { get; set; }
        public Nullable<int> SecondCategoryId { get; set; }
        public Nullable<int> FirstCategoryId { get; set; }
        public Nullable<int> PublicationPlaceId { get; set; }
        public Nullable<int> TranslatorId { get; set; }
        public Nullable<int> PublisherId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual Language Language { get; set; }
        public virtual PadidAvar PadidAvar { get; set; }
        public virtual PermissionState PermissionState { get; set; }
        public virtual PublicationPlace PublicationPlace { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual PublishState PublishState { get; set; }
        public virtual Translator Translator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Content> Contents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentNarratorRelation> DocumentNarratorRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentResourceRelation> DocumentResourceRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSubjectRelation> DocumentSubjectRelations { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
