//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileId { get; set; }
        public int ContentId { get; set; }
        public int FileTypeId { get; set; }
        public Nullable<int> FileNumber { get; set; }
        public int? ResourceId { get; set; }
        public string DeletionDescription { get; set; }
        public string Comment { get; set; }
        public string Text { get; set; }
        public string FileName { get; set; }
        public int? EditorId { get; set; }
    
        public virtual Editor Editor { get; set; }
        public virtual FileType FileType { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Content Content { get; set; }
    }
}
