//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileId { get; set; }
        public int ContentId { get; set; }
        public int FileTypeId { get; set; }
        public int FileNumber { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public string DeletionDescription { get; set; }
        public string Comment { get; set; }
        public string Text { get; set; }
        public string FileName { get; set; }
        public Nullable<int> EditorId { get; set; }
        public Nullable<bool> IsUploaded { get; set; }
        public Nullable<int> FileCode { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Part { get; set; }
        public string Time { get; set; }
        public string Volume { get; set; }
        public string FilePath { get; set; }
    
        public virtual Editor Editor { get; set; }
        public virtual FileType FileType { get; set; }
        public virtual Content Content { get; set; }
        public virtual Resource Resource { get; set; }
    }
}
