//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PadidAvar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PadidAvar()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int PadidAvarId { get; set; }
        public string PadidAvarTitle { get; set; }
        public string BirthDate { get; set; }
        public string DeathDate { get; set; }
        public string SamplePadidAvarTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
    }
}
